services:
  postgres:
    image: postgres:latest
    container_name: gobnb-postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE:-gobnb}
      POSTGRES_USER: ${DB_USER:-gobnb}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/
volumes:
  postgres_data: